pipeline {
    // Uncomment and specify Docker images if needed for specific stages
    // agent { docker { image 'maven:3.6.3'} }
    // agent { docker { image 'node:13.8'} }
    agent any
    
    environment {
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    
    stages {
        stage('checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'github-jenkins',
                url: 'git@github.com:Myprojectaz/firstpipeline.git'

            sh "ls -lat"
            }
        }
        
        stage ('compile') {
            steps {
                // Change directory to where the pom.xml file is located
                dir('simple-java-maven-app/pom.xml') {
                    sh "mvn clean compile"
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('simple-java-maven-app/pom.xml') {
                    sh "mvn test"
                }
            }
        }

        stage ('integration test') {
            steps {
                dir('simple-java-maven-app/pom.xml') {
                    sh "mvn failsafe:integration-test failsafe:verify"
                }
            }
        }
        
        stage('deploy') {
            steps {
                echo 'deploy stage'
            }
        }
    }
}
