pipeline {
     agent {
        docker {
            image 'maven:3.6.3'
            args '-v /root/.m2:/root/.m2' // Mounting Maven cache if needed
        }
    }

    stages {
        stage ('build') {
            steps {
                sh 'mvn --version'
                echo "build"
            }
        }
        stage ('Test') {
            steps {
                echo "Test"
            }
        }
        stage ('integration test') {
            steps {
                echo "integration test"
            }
        }

}
    
}
